### ISSUE TITLE
Metaclass handling

### ISSUE THREAD

**Issue by FasterSpeeding** [ariebovenberg/slotscheck#106]
Right now a metaclass declaration will lead to either an error like `ERROR: 'test:FooMeta' has no slots, but it could have.` if it doesn't declare slots (and the require-subclass config is True) or an exception like the following being raised if it does declare `__slots__`:

```py
Traceback (most recent call last):
  File "C:\Users\Lucina\.pyenv\pyenv-win\versions\3.10.6\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lucina\.pyenv\pyenv-win\versions\3.10.6\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\slotscheck\__main__.py", line 4, in <module>
    root()
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\slotscheck\cli.py", line 201, in root
    messages = list(
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\slotscheck\cli.py", line 548, in slot_messages
    if slots_overlap(c):
  File "C:\Users\Lucina\Documents\VSC\Alluka\venv\lib\site-packages\slotscheck\checks.py", line 34, in slots_overlap
    for ancestor in c.mro()[1:]:
TypeError: unbound method type.mro() needs an argument
```

with the code this was run over being 

```py
class FooMeta(type):
    __slots__ = ()


class Foo(metaclass=FooMeta):
    __slots__ = ()
```

(where FooMeta is the meta class and v0.14.1 of slotscheck was used)

**Comment by ariebovenberg** [comment]
Great find! I'll have a look at this later, or you can submit a fix yourself if you like 🙂
