### ISSUE TITLE
exception raised

### ISSUE THREAD

**Issue by Goldziher** [ariebovenberg/slotscheck#90]
Hi there,

I'm running this library as a pre-commit hook. I introduced some changes, and do have an issue in my code I need to fix - but this causes `slotscheck` to go heywire:

```shell
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 495, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/__init__.py", line 3, in <module>
    from .app import Starlite
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/app.py", line 19, in <module>
    from starlite.asgi import StarliteASGIRouter
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/asgi.py", line 10, in <module>
    from starlite.routes import ASGIRoute, HTTPRoute
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/routes.py", line 20, in <module>
    from starlite.controller import Controller
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/controller.py", line 6, in <module>
    from starlite.handlers import BaseRouteHandler
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/handlers/__init__.py", line 3, in <module>
    from .http import HTTPRouteHandler, delete, get, patch, post, put, route
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/handlers/http.py", line 54, in <module>
    class HTTPRouteHandler(BaseRouteHandler):
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/handlers/http.py", line 256, in HTTPRouteHandler
    def resolve_exception_handlers(self) -> Dict[Union[int, Type[Exception], ExceptionHandler]]:
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 1143, in __getitem__
    _check_generic(self, params, self._nparams)
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/typing_extensions.py", line 103, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for typing.Dict; actual 1, expected 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/slotscheck/__main__.py", line 4, in <module>
    root()
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/slotscheck/cli.py", line 163, in root
    classes, modules = _collect(files, module, conf)
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/slotscheck/cli.py", line 382, in _collect
    modules_all = consolidate(
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/slotscheck/discovery.py", line 46, in consolidate
    for t in trees:
  File "/Users/naamanhirschfeld/.cache/pre-commit/repotvckiflq/py_env-python3.10/lib/python3.10/site-packages/slotscheck/discovery.py", line 158, in module_tree
    loader = pkgutil.get_loader(module)
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 481, in get_loader
    return find_loader(fullname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 501, in find_loader
    raise ImportError(msg.format(fullname, type(ex), ex)) from ex
ImportError: Error while finding loader for 'starlite.controller' (<class 'TypeError'>: Too few parameters for typing.Dict; actual 1, expected 2)
```

**Comment by Goldziher** [comment]
So the bug I had was this:

```python
def resolve_exception_handlers(self) -> Dict[Union[int, Type[Exception]], ExceptionHandler]]:
```

which as you can see had the `Dict` type wrong, the fix:

```python
def resolve_exception_handlers(self) -> Dict[Union[int, Type[Exception], ExceptionHandler]:
```

In either case - this shouldn't cause this kind of error IMO

**Comment by ariebovenberg** [comment]
@Goldziher thanks for opening this issue, I'll have a look

**Comment by ariebovenberg** [comment]
I've found the cause: I didn't account for `pkgutil.get_loader` trying to import parent packages:

```
slotscheck starlite  # ok
slotscheck starlite/controller.py  # not ok
```

This behavior isn't needed for `slotscheck`, but cannot be opted-out. Solution is either to implement a `get_loader` equivalent, or simply abort a `slotscheck` run entirely when such an error occurs (not so nice either).

This will take some time to reliably fix. 

In the meantime, if this problem is too annoying, you could set the pre-commit hook to always run on the root module (and set `pass_filenames` to `false`), but this of course is not how pre-commit is intended to function.

Note: Another issue for which we may consider re-implementing something from the stdlib: #57

**Comment by ariebovenberg** [comment]
On second thought, option (b) is better. In the end we need to import parent packages anyway, so might as well stop immediately with a brief message. New release should be out soon.

@Goldziher You will now get this message:

```
ERROR: Couldn't inspect module 'starlite.controller' due to ImportError("Error while finding loader for 'starlite.controller' (<class 'TypeError'>: Too few parameters for typing.Dict; actual 1, expected 2)"). Run `import starlite.controller` to reproduce this error.
```
